game.resources = [
  { name: 'blackthing', type: 'image', src: 'data/img/blackthing.png' },
  { name: 'end', type: 'image', src: 'data/img/end.png' },
  { name: 'final', type: 'tmx', src: 'data/map/final.tmx' },
  { name: 'finalbg', type: 'image', src: 'data/map/finalbg.png' },
  { name: 'greenthing', type: 'image', src: 'data/img/greenthing.png' },
  { name: 'introbackground', type: 'image', src: 'data/map/introbackground.png' },
  { name: 'intro', type: 'tmx', src: 'data/map/intro.tmx' },
  { name: 'Ld29final', type: 'audio', src: 'data/sfx/' },
  { name: 'Ld29p1', type: 'audio', src: 'data/sfx/' },
  { name: 'Ld29p2', type: 'audio', src: 'data/sfx/' },
  { name: 'levelone', type: 'tmx', src: 'data/map/levelone.tmx' },
  { name: 'leveloneb', type: 'tmx', src: 'data/map/leveloneb.tmx' },
  { name: 'levelonebg', type: 'image', src: 'data/map/levelonebg.png' },
  { name: 'levelthree', type: 'tmx', src: 'data/map/levelthree.tmx' },
  { name: 'levelthreebg', type: 'image', src: 'data/map/levelthreebg.png' },
  { name: 'leveltwo', type: 'tmx', src: 'data/map/leveltwo.tmx' },
  { name: 'leveltwobg', type: 'image', src: 'data/map/leveltwobg.png' },
  { name: 'messageone', type: 'image', src: 'data/img/messageone.png' },
  { name: 'messagetwo', type: 'image', src: 'data/img/messagetwo.png' },
  { name: 'metatiles32x32', type: 'image', src: 'data/map/metatiles32x32.png' },
  { name: 'player', type: 'image', src: 'data/img/player.png' },
  { name: 'redthing', type: 'image', src: 'data/img/redthing.png' },
  { name: 'tiles', type: 'image', src: 'data/map/tiles.png' }
];
