game.resources = [
  { name: 'atlas', type: 'image', src: 'data/img/atlas.png' },
  { name: 'atlas', type: 'json', src: 'data/img/atlas.json' },
  { name: 'final', type: 'tmx', src: 'data/map/final.tmx' },
  { name: 'finalbg', type: 'image', src: 'data/map/finalbg.png' },
  { name: 'introbackground', type: 'image', src: 'data/map/introbackground.png' },
  { name: 'intro', type: 'tmx', src: 'data/map/intro.tmx' },
  { name: 'ld29final', type: 'audio', src: 'data/sfx/' },
  { name: 'ld29p1', type: 'audio', src: 'data/sfx/' },
  { name: 'ld29p2', type: 'audio', src: 'data/sfx/' },
  { name: 'levelone', type: 'tmx', src: 'data/map/levelone.tmx' },
  { name: 'leveloneb', type: 'tmx', src: 'data/map/leveloneb.tmx' },
  { name: 'levelonebg', type: 'image', src: 'data/map/levelonebg.png' },
  { name: 'levelthree', type: 'tmx', src: 'data/map/levelthree.tmx' },
  { name: 'levelthreebg', type: 'image', src: 'data/map/levelthreebg.png' },
  { name: 'leveltwo', type: 'tmx', src: 'data/map/leveltwo.tmx' },
  { name: 'leveltwobg', type: 'image', src: 'data/map/leveltwobg.png' },
  { name: 'metatiles32x32', type: 'image', src: 'data/map/metatiles32x32.png' },
  { name: 'tiles', type: 'image', src: 'data/map/tiles.png' }
];
